const SUPABASE_URL='https://fzrtvogirhmnbicdaffc.supabase.co';
const SUPABASE_KEY='sb_publishable_oHmuwX8xm8d-77XLapdBFw_ragbZH4F';
const ADMIN_SESSION_KEY='visuplanner-platform-admin';
let session=null;
const $=id=>document.getElementById(id),esc=value=>String(value||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function auth(email,password){const r=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=password`,{method:'POST',headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({email,password})});if(!r.ok)throw new Error('Forkert administratorlogin.');return r.json()}
async function api(path,options={}){const r=await fetch(path,{...options,headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json',...(options.headers||{})}});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Handlingen kunne ikke gennemføres.');return data}
function status(text){$('adminStatus').textContent=text;setTimeout(()=>$('adminStatus').textContent='',2200)}
async function openDashboard(){const {teams}=await api('/api/platform-admin');$('adminLoginCard').hidden=true;$('adminDashboard').hidden=false;$('teamCards').innerHTML=teams.map(team=>`<article class="team-card" data-team="${esc(team.slug)}"><h3>${esc(team.name)}</h3><p class="team-meta">${esc(team.municipality)} · ${esc(team.workplace)}</p><div class="team-fields"><label>Ansvarlig arbejdsmail<input data-field="recovery_email" type="email" value="${esc(team.recovery_email)}"></label><label>Ny midlertidig personalekode<input data-field="editor_password" type="password" minlength="6" placeholder="Mindst 6 tegn"></label><label>Ny beboer-/tavlekode<input data-field="viewer_password" type="password" minlength="6" placeholder="Mindst 6 tegn"></label></div><p class="help">Du kan sætte en ny kode, men du kan aldrig se teamets nuværende kode.</p><div class="team-actions"><a class="button secondary" href="/${esc(team.slug)}">Åbn tavlen</a><button data-action="save-contact">Gem kontaktmail</button><button data-action="reset-editor">Nulstil personalekode</button><button data-action="reset-viewer" class="danger">Nulstil tavlekode</button></div></article>`).join('');bindActions()}
function bindActions(){document.querySelectorAll('[data-action]').forEach(button=>button.onclick=async()=>{const card=button.closest('[data-team]'),slug=card.dataset.team,action=button.dataset.action;const field=action==='save-contact'?'recovery_email':action==='reset-editor'?'editor_password':'viewer_password';const value=card.querySelector(`[data-field="${field}"]`).value.trim();if(!value)return status('Udfyld feltet først.');if(field.endsWith('password')&&!confirm('Vil du sætte en ny kode? Den gamle kode stopper med at virke.'))return;button.disabled=true;try{await api('/api/platform-admin',{method:'POST',body:JSON.stringify({slug,action,value})});card.querySelector(`[data-field="${field}"]`).value=field==='recovery_email'?value:'';status('Ændringen er gemt.')}catch(e){status(e.message)}finally{button.disabled=false}})}
$('platformLoginForm').onsubmit=async event=>{event.preventDefault();$('platformLoginError').textContent='';try{session=await auth($('platformEmail').value.trim(),$('platformPassword').value);sessionStorage.setItem(ADMIN_SESSION_KEY,JSON.stringify(session));await openDashboard()}catch(e){$('platformLoginError').textContent=e.message}};
$('platformLogout').onclick=()=>{sessionStorage.removeItem(ADMIN_SESSION_KEY);location.reload()};
(async()=>{try{session=JSON.parse(sessionStorage.getItem(ADMIN_SESSION_KEY));if(session?.access_token)await openDashboard()}catch{sessionStorage.removeItem(ADMIN_SESSION_KEY)}})();
document.addEventListener('click',event=>{const link=event.target.closest('a[href^="/team-"]');if(link&&session)sessionStorage.setItem('visuplanner-session',JSON.stringify(session))});
