const DEMO_DAYS=[['Man','MANDAG','#eab308'],['Tir','TIRSDAG','#ef4444'],['Ons','ONSDAG','#22c55e'],['Tor','TORSDAG','#f97316'],['Fre','FREDAG','#3b82f6'],['Lør','LØRDAG','#a855f7'],['Søn','SØNDAG','#ec4899']];
const DEMO_STAFF=[['Anna','00'],['Jonas','01'],['Lene','02'],['Mikkel','03'],['Henrik','04'],['Sofie','05'],['Fatima','06'],['Noah','07']].map(([name,id])=>({name,photo:`/assets/demo-staff/person-${id}.webp`}));
const KEY='visuplanner-demo-session';
const blank=()=>({morning:['',''],evening:['',''],night:['',''],dinner:'',activities:[]});
let week=JSON.parse(sessionStorage.getItem(KEY)||'null')||DEMO_DAYS.map(blank),selected=(new Date().getDay()+6)%7,editActivities=[];
const $=id=>document.getElementById(id),esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function monday(){const d=new Date(),n=d.getDay()||7;d.setDate(d.getDate()-n+1);d.setHours(12,0,0,0);return d}function dateAt(i){const d=monday();d.setDate(d.getDate()+i);return d}function fmt(d){return new Intl.DateTimeFormat('da-DK',{day:'numeric',month:'long'}).format(d)}
function people(id,names){$(id).innerHTML=names.filter(Boolean).length?names.filter(Boolean).map(name=>{const p=DEMO_STAFF.find(x=>x.name===name);return `<div class="person demo-person"><img src="${p.photo}" alt=""><span>${esc(name)}</span></div>`}).join(''):'<p class="empty">Ikke udfyldt</p>'}
function render(){const d=week[selected];document.documentElement.style.setProperty('--day-color',DEMO_DAYS[selected][2]);$('demoDay').textContent=DEMO_DAYS[selected][1];$('demoDate').textContent=fmt(dateAt(selected));people('demoMorning',d.morning);people('demoEvening',d.evening);people('demoNight',d.night);$('demoDinner').textContent=d.dinner||'Ikke udfyldt';$('demoActivities').innerHTML=d.activities.length?d.activities.map(a=>`<div class="activity"><div class="activity-time">${esc(a.time)}</div><div class="activity-name">${esc(a.name)}</div></div>`).join(''):'<p class="empty">Ingen aktiviteter</p>';$('demoDayTabs').innerHTML=DEMO_DAYS.map((x,i)=>`<button class="day-tab ${i===selected?'active':''}" data-day="${i}"><span>${x[0]}</span><small>${dateAt(i).getDate()}.${dateAt(i).getMonth()+1}</small></button>`).join('');document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{selected=+b.dataset.day;render()})}
function options(value=''){return '<option value="">Vælg medarbejder</option>'+DEMO_STAFF.map(p=>`<option ${p.name===value?'selected':''}>${p.name}</option>`).join('')}
function loadEditor(){const d=week[selected];$('demoEditDay').value=selected;['Morning1','Morning2','Evening1','Evening2','Night1','Night2'].forEach((suffix,i)=>{const type=i<2?'morning':i<4?'evening':'night',slot=i%2;$(`demo${suffix}`).innerHTML=options(d[type][slot])});$('demoDinnerInput').value=d.dinner;editActivities=structuredClone(d.activities);renderActivityEditor()}
function renderActivityEditor(){$('demoActivityEditor').innerHTML=editActivities.length?editActivities.map((a,i)=>`<div class="demo-activity-edit"><input type="time" value="${esc(a.time)}" data-demo-index="${i}" data-demo-field="time"><input value="${esc(a.name)}" placeholder="Aktivitet" data-demo-index="${i}" data-demo-field="name"><button type="button" data-demo-remove="${i}">✕</button></div>`).join(''):'<p class="empty">Ingen aktiviteter endnu.</p>';document.querySelectorAll('[data-demo-field]').forEach(x=>x.oninput=()=>editActivities[+x.dataset.demoIndex][x.dataset.demoField]=x.value);document.querySelectorAll('[data-demo-remove]').forEach(x=>x.onclick=()=>{editActivities.splice(+x.dataset.demoRemove,1);renderActivityEditor()})}
function status(t){$('demoStatus').textContent=t;setTimeout(()=>$('demoStatus').textContent='',1800)}
$('demoPrev').onclick=()=>{selected=(selected+6)%7;render()};$('demoNext').onclick=()=>{selected=(selected+1)%7;render()};$('demoAdminButton').onclick=()=>{$('demoPin').value='';$('demoLoginError').textContent='';$('demoLoginDialog').showModal()};$('demoLoginClose').onclick=()=>$('demoLoginDialog').close();$('demoLoginForm').onsubmit=e=>{e.preventDefault();if($('demoPin').value!=='1234'){ $('demoLoginError').textContent='Forkert kode. Demokoden er 1234.';return}$('demoLoginDialog').close();loadEditor();$('demoEditorDialog').showModal()};$('demoEditorClose').onclick=()=>$('demoEditorDialog').close();$('demoEditDay').innerHTML=DEMO_DAYS.map((d,i)=>`<option value="${i}">${d[1]} ${fmt(dateAt(i))}</option>`);$('demoEditDay').onchange=()=>{selected=+$('demoEditDay').value;loadEditor();render()};$('demoAddActivity').onclick=()=>{editActivities.push({time:'10:00',name:''});renderActivityEditor()};$('demoSave').onclick=()=>{const d=week[selected];d.morning=[$('demoMorning1').value,$('demoMorning2').value];d.evening=[$('demoEvening1').value,$('demoEvening2').value];d.night=[$('demoNight1').value,$('demoNight2').value];d.dinner=$('demoDinnerInput').value.trim();d.activities=editActivities.filter(a=>a.name.trim());sessionStorage.setItem(KEY,JSON.stringify(week));render();$('demoEditorDialog').close();status('Dagen er gemt i denne browserfane')};$('demoReset').onclick=()=>{if(!confirm('Vil du nulstille hele demoen?'))return;week=DEMO_DAYS.map(blank);sessionStorage.removeItem(KEY);render();loadEditor();status('Demoen er nulstillet')};render();
